# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5f93cb403d0481a7ab2afd34c6ad4a4a750953ee68860d4be0bcb456cf9f4aa77e26df0f79a69c8a36a4f4a05db846694acde157361345272bef61f47343a93

test:
  secret_key_base: 7d87c0b928c1f0def47ffadb15c0183b9156da72bf4c367fff91c0cdc432423b186d9aa18f953cef07a8ac23e1fc3a29a35fb704d6b486c6b2e84f4b96ce6862

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
